# ─────────────────────────────────────────────────────────────
# Create the ExEco Index (Metadata Dataframe)
# ─────────────────────────────────────────────────────────────

library(dplyr)

# Transform the nested list into a flat dataframe without the "text" column
ExEco_df <- dplyr::bind_rows(lapply(ExEco_Dataset, function(x) {
  
  # Remove the "text" element from each entry to keep only metadata
  x$text <- NULL
  
  # Safely clean and extract values for each metadata field
  x_clean <- lapply(x, function(val) {
    
    # unlist() flattens sneaky nested structures like list(NULL) or list(list()) 
    # often generated by JSON parsers, which bypass simple length() == 0 checks.
    flat_val <- unlist(val)
    
    # Check if the flattened value is truly empty (NULL, character(0), logical(0))
    if (length(flat_val) == 0) {
      return(NA_character_)
    } else {
      # Extract strictly the first element to guarantee length == 1.
      # This prevents the "arguments imply differing number of rows: 1, 0" error.
      return(flat_val[1])
    }
  })
  
  # Convert each cleaned article entry to a single-row dataframe
  as.data.frame(x_clean, stringsAsFactors = FALSE)
}))

# Reset row names to avoid keeping the original list names as row indices
rownames(ExEco_df) <- NULL

# (Optional) Quick validation output
message(sprintf("​📋​ ExEco_df index successfully created with %d rows and %d columns.", 
                nrow(ExEco_df), ncol(ExEco_df)))